# Use the Python 3.17 Alpine base image as the builder
FROM python:alpine3.17 as builder

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt file into the working directory
COPY consume/requirements.txt .

# Update package index and install build dependencies, then install the Python packages from requirements.txt
RUN apk update && \
    apk add --no-cache build-base && \
    pip install --no-cache-dir --prefix=/install -r requirements.txt

# Start a new build stage using the Python 3.17 Alpine base image
FROM python:alpine3.17

# Set the working directory to /app
WORKDIR /app

# Copy the installed packages from the builder stage
COPY --from=builder /install /usr/local

# Copy the consume directory content into the working directory
COPY consume .

# Set the default command for the container to run consume.py
CMD ["python", "consume.py"]
